use company;

CREATE TABLE SALES_DATA(
SALE_ID INT PRIMARY KEY,
SALESMAN VARCHAR(50),
REGION VARCHAR(50),
PRODUCT varchar(50),
AMOUNT DECIMAL(10,2)
);

INSERT INTO SALES_DATA (SALE_ID, SALESMAN, REGION, PRODUCT, AMOUNT) VALUES
(1, 'GAURAV', 'NORTH', 'LAPTOP', 50000),
(2, 'ADITYA', 'SOUTH', 'MOBILE', 20000),
(3, 'NEHA', 'NORTH', 'TABLET', 15000),
(4, 'RAHUL', 'EAST', 'LAPTOP', 60000),
(5, 'ANITA', 'WEST', 'MOBILE', 25000),
(6, 'ROHAN', 'NORTH', 'MOBILE', 22000),
(7, 'PRIYA', 'SOUTH', 'LAPTOP', 55000),
(8, 'AMIT', 'EAST', 'TABLET', 18000),
(9, 'GAUTAM', 'WEST', 'LAPTOP', 40000),
(10,'BALRAM', 'NORTH', 'TABLET', 30000);

SELECT * FROM SALES_DATA;

-- Aggregate Functions

SELECT SUM(AMOUNT) AS TOTAL_SALE FROM SALES_DATA;
SELECT AVG(AMOUNT) AS AVARAGE_SALE FROM SALES_DATA;
SELECT MAX(AMOUNT) AS HIGHEST_SALE FROM SALES_DATA;
SELECT MIN(AMOUNT) AS LOWEST_SALE FROM SALES_DATA;
SELECT COUNT(*) AS TOTAL_RECORDS FROM SALES_DATA;


-- Aggregate Functions with WHERE CLAUSE (row filter)

SELECT SALESMAN, AMOUNT
FROM SALES_DATA
WHERE AMOUNT = (SELECT MAX(AMOUNT) FROM SALES_DATA);   -- HIGHEST SELLER

SELECT COUNT(*) AS HIGH_VALUE_SALES
FROM SALES_DATA
WHERE AMOUNT > 30000;


-- Aggregate Functions with GROUP BY CLAUSE (grouping)

SELECT REGION, SUM(AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY REGION;

SELECT REGION, PRODUCT, COUNT(PRODUCT) AS PRODUCT_QUANTITY
FROM SALES_DATA
GROUP BY PRODUCT,REGION;

SELECT PRODUCT, COUNT(PRODUCT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY PRODUCT;

-- Aggregate Functions with HAVING CLAUSE (group filter)

SELECT REGION, SUM(AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY REGION
HAVING SUM(AMOUNT) > 100000;

SELECT PRODUCT, AVG(AMOUNT) AS AVG_SALES
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(AMOUNT) < 25000;

SELECT SALESMAN, SUM(AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
GROUP BY SALESMAN
HAVING SUM(AMOUNT) >= 50000;


-- (WHERE + GROUP BY + HAVING + ORDER BY) full example together

SELECT REGION, SUM(AMOUNT) AS TOTAL_SALES
FROM SALES_DATA
WHERE PRODUCT = 'LAPTOP'              -- Step 1: Laptops rows filter
GROUP BY REGION                       -- Step 2: GROUP BY REGION
HAVING SUM(AMOUNT) > 50000           -- Step 3: filter grouped REGION when total sales > 50000
ORDER BY REGION DESC;
