CREATE DATABASE Company;
create database If Not Exists COMPANY2;
drop database company2;

SHOW DATABASES;
USE COMPANY;
SHOW TABLES;

CREATE TABLE EMPLOYEEINFO(
EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50) NOT NULL,
DESIGNATION VARCHAR(30) NOT NULL,
MOBILE VARCHAR(10)
);

ALTER TABLE EMPLOYEEINFO ADD EMAIL VARCHAR(100);
ALTER TABLE EMPLOYEEINFO MODIFY EMAIL VARCHAR(150);
ALTER TABLE EMPLOYEEINFO CHANGE EMAIL EMAIL_ID VARCHAR(100);
ALTER TABLE EMPLOYEEINFO RENAME EMPLOYEE_DETAIL;
ALTER TABLE EMPLOYEE_DETAIL DROP COLUMN EMAIL_ID;


INSERT INTO EMPLOYEE_DETAIL (EMPLOYEE_ID, EMPLOYEE_NAME, DESIGNATION, MOBILE) VALUES 
(1, 'GAURAV', 'PYTHON DEVELOPER', 7505399720),
(2, 'NEHA SHARMA', 'JAVA DEVELOPER', 9876543210),
(3, 'RAHUL VERMA', 'DATA ANALYST', 9123456780),
(4, 'ANITA MEHTA', 'PROJECT MANAGER', 9988776655),
(5, 'ROHAN KAPOOR', 'WEB DESIGNER', 8899001122),
(6, 'PRIYA SINGH', 'DATABASE ADMIN', 7766554433),
(7, 'AMIT KUMAR', 'NETWORK ENGINEER', 7001122334);

REPLACE INTO EMPLOYEE_DETAIL (EMPLOYEE_ID, EMPLOYEE_NAME, DESIGNATION, MOBILE) VALUES
(3, 'SAURAV', 'JAVA DEVELOPER', 9876543210);

-- TRUNCATE + INSERT = this is the fastest way to clear or delete entire table's content
TRUNCATE TABLE EMPLOYEE_DETAIL;

INSERT INTO EMPLOYEE_DETAIL (EMPLOYEE_ID, EMPLOYEE_NAME, DESIGNATION, MOBILE) VALUES
(1, 'GAURAV', 'PYTHON DEVELOPER', 7545765820),
(2, 'ADITYA', 'JAVA DEVELOPER', 9876543210),
(3, 'AJAY', 'DATA ANALYST', 9123456780),
(4, 'GAUTAM', 'PROJECT MANAGER', 9988776655),
(5, 'BALRAM', 'WEB DESIGNER', 8899001122),
(6, 'HARSH', 'DATABASE ADMIN', 7766554433),
(7, 'HIMANSHU', 'DATA ANALYST', 7001122334);

SELECT *FROM EMPLOYEE_DETAIL;
SELECT EMPLOYEE_NAME, MOBILE FROM EMPLOYEE_DETAIL;

-- USE OF WHERE CLAUSE WITH SELECT STATEMENT

SELECT *FROM EMPLOYEE_DETAIL WHERE DESIGNATION = 'DATA ANALYST';
SELECT *FROM EMPLOYEE_DETAIL WHERE EMPLOYEE_ID >= 3;

-- USE OF DELETE STATEMENT

-- when sql is in safe mode then use this command for you want to delete entire table content
DELETE FROM EMPLOYEE_DETAIL WHERE EMPLOYEE_ID > 0;

-- USE OF UPDATE STATEMENT

UPDATE EMPLOYEE_DETAIL SET MOBILE = 2456580800 WHERE EMPLOYEE_ID = 4;
UPDATE EMPLOYEE_DETAIL SET DESIGNATION = 'SENIOR DEVELOPER' WHERE EMPLOYEE_ID = 1;

UPDATE EMPLOYEE_DETAIL
SET EMPLOYEE_NAME = 'ANCHAL', MOBILE = '1287653501'
WHERE EMPLOYEE_ID = 7;

-- FOREIGN KEY CONSTRAINT EXAMPLE

DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS DEPARTMENTS;

CREATE TABLE DEPARTMENTS (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EMPLOYEES (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50) NOT NULL,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES 
(1,'HR'), 
(2,'IT'), 
(3,'CEO');

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_ID) VALUES
(101,'GAURAV',2),
(102,'ROHIT',1),
(103,'NIKITA',1);

DELETE FROM DEPARTMENTS WHERE DEPT_ID = 1;

UPDATE DEPARTMENTS SET DEPT_ID = 1 WHERE DEPT_ID = 2;

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

SHOW TABLE STATUS WHERE Name = 'EMPLOYEES';
SHOW TABLE STATUS WHERE Name = 'DEPARTMENTS';


-- CHECK CONSTRAINT EXAMPLE

CREATE TABLE SALES_ORDERS (
ORDER_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(50),
QUANTITY INT CHECK (QUANTITY < 5)
);

INSERT INTO SALES_ORDERS (ORDER_ID, PRODUCT_NAME, QUANTITY) VALUES (1, 'SPEAKER', 3), (2,'LAPTOP', 1);
SELECT *FROM SALES_ORDERS;

-- DEFAULT CONSTRAINT EXAMPLE

CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) DEFAULT 'DEHRADUN',           -- default value
    JOIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- default = today
);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME) 
VALUES (1, 'GAURAV');
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, CITY) 
VALUES (2, 'NEHA', 'MUMBAI');

SELECT *FROM EMPLOYEE;


SHOW DATABASES;
USE COMPANY;
SHOW TABLES;