-- DATABASE CREATE
CREATE DATABASE SCHOOL;

SHOW DATABASES;
USE SCHOOL;
SHOW TABLES;

-- STUDENTS TABLE
CREATE TABLE STUDENTS (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    AGE INT,
    CLASS VARCHAR(10)
);

-- TEACHERS TABLE
CREATE TABLE TEACHERS (
    TEACHER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SUBJECT VARCHAR(30)
);

SELECT *FROM STUDENTS;
SELECT *FROM TEACHERS;


SHOW DATABASES;
USE SCHOOL;
SHOW TABLES;
