CREATE DATABASE STUDENT;
USE STUDENT;

CREATE TABLE STUDENT_MARKS(
    ROLL_NO INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(50),
    HINDI INT,
    ENGLISH INT,
    MATHS INT,
    PHYSICS INT,
    CHEMISTRY INT,
    AGE INT,                     -- comparison operator use के लिए
    GENDER VARCHAR(10),          -- IN / NOT IN / LIKE के लिए
    CITY VARCHAR(50),            -- LIKE / pattern match
    SCHOLARSHIP DECIMAL(10,2),   -- arithmetic, >, <, BETWEEN
    ATTENDANCE INT               -- % attendance check करने के लिए
);

INSERT INTO STUDENT_MARKS 
(ROLL_NO, STUDENT_NAME, HINDI, ENGLISH, MATHS, PHYSICS, CHEMISTRY, AGE, GENDER, CITY, SCHOLARSHIP, ATTENDANCE) 
VALUES
(1, 'GAURAV', 78, 82, 91, 85, 79, 20, 'MALE', 'DEHRADUN', 5000.00, 92),
(2, 'NEHA SHARMA', 88, 75, 80, 90, 84, 19, 'FEMALE', 'DELHI', 3000.00, 85),
(3, 'RAHUL VERMA', 67, 70, 72, 65, 69, 21, 'MALE', 'MUMBAI', NULL, 70),
(4, 'ANITA MEHTA', 92, 89, 95, 94, 90, 20, 'FEMALE', 'DELHI', 7000.00, 95),
(5, 'ROHAN KAPOOR', 55, 60, 58, 62, 57, 22, 'MALE', 'DEHRADUN', 0.00, 60),
(6, 'PRIYA SINGH', 85, 87, 90, 88, 86, 19, 'FEMALE', 'LUCKNOW', 4500.00, 88),
(7, 'AMIT KUMAR', 72, 74, 70, 68, 73, 23, 'MALE', 'MUMBAI', NULL, 75),
(8, 'HIMANSHU', 95, 93, 97, 96, 94, 20, 'MALE', 'DEHRADUN', 8000.00, 98),
(9, 'BALRAM', 60, 65, 62, 64, 61, 24, 'MALE', 'DELHI', 0.00, 55),
(10, 'ADITYA', 81, 79, 83, 82, 80, 18, 'MALE', 'PUNE', 2000.00, 90);

SELECT *FROM STUDENT_MARKS;

-- ARITHMETIC OPERATORS (+, -, *, /, %)

SELECT STUDENT_NAME,
       HINDI + ENGLISH + MATHS + PHYSICS + CHEMISTRY AS TOTAL_MARKS
FROM STUDENT_MARKS;

SELECT STUDENT_NAME,
       (HINDI + ENGLISH + MATHS + PHYSICS + CHEMISTRY) / 5 AS AVERAGE_MARKS
FROM STUDENT_MARKS;

SELECT STUDENT_NAME, SCHOLARSHIP, (SCHOLARSHIP * 1.10) AS NEW_SCHOLARSHIP
FROM STUDENT_MARKS;

-- COMPARISON OPERATORS (=, <, >, <=, >=, != or <>)

SELECT *FROM STUDENT_MARKS
WHERE STUDENT_NAME = 'NEHA SHARMA';

SELECT *FROM STUDENT_MARKS
WHERE ENGLISH <> 65;            -- != OR <>

SELECT *FROM STUDENT_MARKS
WHERE ENGLISH > 80;

SELECT *FROM STUDENT_MARKS
WHERE ENGLISH < 80;

SELECT *FROM STUDENT_MARKS
WHERE CHEMISTRY >= 90;

SELECT *FROM STUDENT_MARKS
WHERE CHEMISTRY <= 70;

-- LOGICAL OPERATORS (AND,OR,NOT)

SELECT *FROM STUDENT_MARKS
WHERE PHYSICS >= 90 AND PHYSICS <= 95;

SELECT *FROM STUDENT_MARKS
WHERE PHYSICS <= 70 OR MATHS <= 70;

SELECT * FROM STUDENT_MARKS 
WHERE SCHOLARSHIP > 5000 OR ATTENDANCE > 95;

SELECT *FROM STUDENT_MARKS
WHERE NOT HINDI <= 75;

SELECT * FROM STUDENT_MARKS 
WHERE NOT CITY = 'DELHI';

-- BETWEEN OPERATOR (RANGE FROM X TO Y)

SELECT * FROM STUDENT_MARKS WHERE PHYSICS BETWEEN 70 AND 90;
SELECT * FROM STUDENT_MARKS WHERE SCHOLARSHIP BETWEEN 2000 AND 6000;

-- IN Operator

SELECT * FROM STUDENT_MARKS WHERE CITY IN ('DELHI', 'MUMBAI');
SELECT * FROM STUDENT_MARKS WHERE STUDENT_NAME IN ('NEHA SHARMA','PRIYA SINGH','ANITA MEHTA');

-- LIKE OPERATOR

SELECT * FROM STUDENT_MARKS WHERE STUDENT_NAME LIKE 'G%';      -- STARTS WITH G
SELECT * FROM STUDENT_MARKS WHERE STUDENT_NAME LIKE '%RA%';	   -- RA IN MIDDLE
SELECT * FROM STUDENT_MARKS WHERE STUDENT_NAME LIKE '%A';      -- ENDS WITH A

-- IS NULL / IS NOT NULL OPERATOR

SELECT * FROM STUDENT_MARKS WHERE SCHOLARSHIP IS NULL;
SELECT * FROM STUDENT_MARKS WHERE SCHOLARSHIP IS NOT NULL;

-- ORDER BY CLAUSE (Ascending / Descending)

SELECT * FROM STUDENT_MARKS ORDER BY STUDENT_NAME ASC;            -- A TO Z

SELECT * FROM STUDENT_MARKS ORDER BY STUDENT_NAME DESC;             -- Z TO A

SELECT STUDENT_NAME, MATHS FROM STUDENT_MARKS ORDER BY MATHS DESC;    -- HIGH TO LOW

SELECT STUDENT_NAME, ENGLISH FROM STUDENT_MARKS ORDER BY ENGLISH ASC;   -- LOW TO HIGH

-- LIMIT CLAUSE (Top-N Records)

SELECT STUDENT_NAME, CHEMISTRY 
FROM STUDENT_MARKS 
ORDER BY MATHS DESC 
LIMIT 3;

SELECT * FROM STUDENT_MARKS LIMIT 2;       -- show starting 2 records

SELECT * FROM STUDENT_MARKS LIMIT 2, 3;    -- show 3 records after skip starting 2 records
