"""add age column to users table

Revision ID: 0c0540603080
Revises: 887aa699515f
Create Date: 2026-09-22 18:09:01.058819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0540603080'
down_revision: Union[str, Sequence[str], None] = '887aa699515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alembic_users', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alembic_users', 'age')
    # ### end Alembic commands ###
